#!/usr/bin/perl
use strict;

my $name = (shift(@ARGV) or 'data');
print "char $name\[] = {\n";

for (;;) {
    my $data;
    my $ndata = read(\*STDIN, $data, 1024);
    last if not $ndata;
    for (my $i = 0; $i < $ndata; ++$i) {
        print ord(substr $data, $i, 1), ',';
    }
}
print "0};\n";
