char help[] = {

"By default, output is a visual representation of the tiled board.\n"
"The -l flag produces a list representation of the placement of each tile instead.\n"
"Using both -l and -v produces both the visual and list output.\n"
"\n"
"A board file contains a sequence of shape description lines.\n"
"Each shape description line describes one horizontal row of cells in a shape.\n"
"A line consists of a sequence of asterisks and dots; spaces are ignored.\n"
"An asterisk represents a cell which belongs to the shape, whereas a dot \n"
"represents an empty cell, a cell which does not belong to the shape.\n"
"For example, this board file represents an 8x8 board with the corners removed:\n"
"    .******.\n"
"    ********\n"
"    ********\n"
"    ********\n"
"    ********\n"
"    ********\n"
"    ********\n"
"    .******.\n"
"The final dot in the first and last line could be omitted.\n"
"\n"
"A tile file contains a sequence of tile descriptors.\n"
"A tile descriptor consists of a line \"tile NAME\" which names the tile,\n"
"followed by a sequence of one or more shape description lines, \n"
"followed by a line consisting of the word \"end\".\n"
"\n"
"If NAME consists of two strings separated by a slash, \n"
"the first string is used as the name of the tile in its normal orientation \n"
"and the second string is used as the name when the tile is reversed.\n"
"If there is no slash, the reversed name is the tile's name with the\n"
"case of the first letter inverted.\n"
"\n"
"For example, this tile file describes two pentominoes:\n"
"    tile F\n"
"    .**\n"
"    **\n"
"    .*\n"
"    end\n"
"    tile U\n"
"    *.*\n"
"    ***\n"
"    end\n"
"\n"

};
