char help1[] = {

"usage: tiles [-vVl] [-crsu1][-n#][-i#][-W#,#] [-p][-x][-t TILES] BOARD\n"
"       -v = print ASCII picture for each solution\n"
"       -V = print better ASCII picture for each solution\n"
"       -l = print list of tiles for each solution\n"
"\n"
"       -c = suppress count of solutions\n"
"       -n = print only first N solutions\n"
"       -1 = same as -n1\n"
"       -i = left indent\n"
"       -r = don't suppress rotations and reflections\n"
"       -R = don't reverse tiles\n"
"       -s = print extra spaces for alignment in -l output\n"
"       -u = use reversed name for reversed tiles in -v output\n"
"       -W = size of -V cells\n"
"\n"
"       -p = use pentomino tiles\n"
"       -x = use hexomino tiles\n"
"       -t = use tiles described in TILES file\n"
"       BOARD is either a file containing a board description,\n"
"                or \"NxM\" (integer N,M) for a rectangular board\n"

};

char help2[] = {

"By default (-v), output is a visual representation of the tiled board\n"
"with one letter for each cell in the board.\n"
"The -V flag produces an ASCII art depiction of the board.\n"
"The -l flag produces a list representation of the placement of each tile.\n"
"\n"
"A board may be specified by a board description or a board file.\n"
"1. A board file contains a sequence of shape description lines.\n"
"Each shape description line describes one horizontal row of cells in a shape.\n"
"A line consists of a sequence of asterisks and dots; spaces are ignored.\n"
"An asterisk represents a cell which belongs to the shape, whereas a dot \n"
"represents an empty cell, a cell which does not belong to the shape.\n"
"For example, this board file represents an 8x8 board with the corners removed:\n"
"    .******.\n"
"    ********\n"
"    ********\n"
"    ********\n"
"    ********\n"
"    ********\n"
"    ********\n"
"    .******.\n"
"The final dot in the first and last line could be omitted.\n"
"2. A board description is a string \"NxM\" where N and M are integers,\n"
"optionally followed by a list of strings \"[+-]X,Y\" to add or remove\n"
"individual squares, or \"[+-]X,Y:NxM\" to add or remove rectangular\n"
"regions in the board.\n"
"For example, this board description specifies the same board as\n"
"the board file above: \"8x8-0,0-0,7-7,0-7,7\".\n"
"\n"
"A tile file contains a sequence of tile descriptors.\n"
"A tile descriptor consists of a line \"tile NAME\" which names the tile,\n"
"followed by a sequence of one or more shape description lines, \n"
"followed by a line consisting of the word \"end\".\n"
"\n"
"If NAME consists of two strings separated by a slash, \n"
"the first string is used as the name of the tile in its normal orientation \n"
"and the second string is used as the name when the tile is reversed.\n"
"If there is no slash, the reversed name is the tile's name with the\n"
"case of the first letter inverted.\n"
"\n"
"For example, this tile file describes two pentominoes:\n"
"    tile F\n"
"    .**\n"
"    **\n"
"    .*\n"
"    end\n"
"    tile U\n"
"    *.*\n"
"    ***\n"
"    end\n"
"\n"

};
