#!/bin/sh

# Summarize ring solutions and print one example of each.

cd ring-sols
for f in $(ls -1 | sort -n); do
    o=$(perl -e '$s=1; while(<>){ $b=/^\s*$/; $s=0 if $s and not $b; if (not $s){ last if $b; print }}' $f)
    d=$(grep " $f\\." ../ring-out)
    n=$(tail -1 $f | sed 's/ .*//')
    if [ $n -gt 0 ]; then echo "$d"; echo "$o"; echo; fi
done
